from miniFasta import fasta_object
from numpy.ma.core import make_mask
import fastq as fq
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

fake_id = "@M00224:169:000000000-B533W:1:1101:15810:1337 1:N:0:1"
ref_seq_r1 = "AGCAATTTAGGTATGAAAGCCAGCTACAGATGGTACAGGTGACCGGCTCCTCAGATAATGAGTACTTCTACGTTGATTTCAGAGAATATGAATATGATCTCAAATGGGAGTTTCCAAGAGAAAATTTAGAGTTTGGTAAGAATGGAATGTGCCAAATGTTTCTGCAGCATTTCTTTTCCATTGGAAAATCTTTAAAATGCACGTACTCACCATTTGTCTTTGCAGGGAAGGTACTAGGATCAGGTGCTTTC"
ref_seq_r2 = "GACTTTCAGCATTTTGACGGCAACCTGGATTGAGACTCCTGTTTTGCTAATTCCATAAGCTGTTGCGTTCATCACTTTTCCAAAAGCACCTGATCCTAGTACCTTCCCTGCAAAGACAAATGGTGAGTACGTGCATTTTAAAGATTTTCCAATGGAAAAGAAATGCTGCAGAAACATTTGGCACATTCCATTCTTACCAAACTCTAAATTTTCTCTTGGAAACTCCCATTTGAGATCATATTCATATTCTC"
ref_record_r1 = SeqRecord(
    Seq(ref_seq_r1),
    id=fake_id,
    name="ABBACFFFFFFFGGGGGGGGGGGHGHGGHHHHHHHGHHHHGHHEFFEFGHHGHHHHGHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHGHHHHGGHHHFHGHFGHHHHGHHHHHGHHHHHHGGGHHHHHHHGHHGHHHHHHFHHFHFFGCDGHHHHHGHHHHFGHHHGGEGFHHHHHGFFFGHHHHGHHHHHDGHGHGGFEGGHHDFHHHHHGHECGHHHHHHHGGHHHHHHHHHGGHHGFFDD",
    description="+",
)
ref_record_r2 = SeqRecord(
    Seq(ref_seq_r2),
    id=fake_id,
    name="ABBACFFFFFFFGGGGGGGGGGGHGHGGHHHHHHHGHHHHGHHEFFEFGHHGHHHHGHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHGHHHHGGHHHFHGHFGHHHHGHHHHHGHHHHHHGGGHHHHHHHGHHGHHHHHHFHHFHFFGCDGHHHHHGHHHHFGHHHGGEGFHHHHHGFFFGHHHHGHHHHHDGHGHGGFEGGHHDFHHHHHGHECGHHHHHHHGGHHHHHHHHHGGHHGFFDD",
    description="-",
)
# 9bp - ATTTGATTT
ins_9 = "GCAATTTAGGTATGAAAGCCAGCTACAGATGGTACAGGTGACCGGCTCCTCAGATAATGAGTACTTCTACGGAATTTGATTTCAGAATTTGATTTGAATTTGATTTTGCGAATATGATCTCAAATGGGAGTTTCCAAGAGAAAATTTAGAGTTTGGTAAGAATGGAATGTGCCAAATGTTTCTGCAGCATTTCTTTTCCATTGGAAAATCTTTAAAATGCACGTACTCACCATTTGTCTTTGCAGGGAAGG"
ins_9_SeqRec = SeqRecord(
    Seq(ins_9),
    id=fake_id,
    name="ABBACFFFFFFFGGGGGGGGGGGHGHGGHHHHHHHGHHHHGHHEFFEFGHHGHHHHGHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHGHHHHGGHHHFHGHFGHHHHGHHHHHGHHHHHHGGGHHHHHHHGHHGHHHHHHFHHFHFFGCDGHHHHHGHHHHFGHHHGGEGFHHHHHGFFFGHHHHGHHHHHDGHGHGGFEGGHHDFHHHHHGHECGHHHHHHHGGHHHHHHHHHGGHHGFFDD",
    description="+",
)
# 21b - TTGATTTCAGAGAATATGAAT
itd_21 = "GCAATTTAGGTATGAAAGCCAGCTACAGATGGTACAGGTGACCGGCTCCTCAGATAATGAGTACTTCTACGTTGATTTCAGAGAATATGAATTTGATTTCAGAGAATATGAATATGATCTCAAATGGGAGTTTCCAAGAGAAAATTTAGAGTTTGGTAAGAATGGAATGTGCCAAATGTTTCTGCAGCATTTCTTTTCCATTGGAAAATCTTTAAAATGCACGTACTCACCATTTGTCTTTGCAGGGAAGG"
itd_21_SeqRec = SeqRecord(
    Seq(itd_21),
    id=fake_id,
    name="ABBACFFFFFFFGGGGGGGGGGGHGHGGHHHHHHHGHHHHGHHEFFEFGHHGHHHHGHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHGHHHHGGHHHFHGHFGHHHHGHHHHHGHHHHHHGGGHHHHHHHGHHGHHHHHHFHHFHFFGCDGHHHHHGHHHHFGHHHGGEGFHHHHHGFFFGHHHHGHHHHHDGHGHGGFEGGHHDFHHHHHGHECGHHHHHHHGGHHHHHHHHHGGHHGFFDD",
    description="+",
)
# 36bp - TATGAATATGATCTTGATTTCAGAGAATATGAATAA
ins_36 = "GCAATTTAGGTATGAAAGCCAGCTACAGATGGTACAGGTGACCGGCTCCTCAGATAATGAGTACTTCTACGTTGATTTCAGAGAATATGAATTTGATTTCAGAGAATATGAATATGATCTTGATTTCAGAGAATATGAATAAAATTTAGAGTTTGGTAAGAATGGAATGTGCCAAATGTTTCTGCAGCATTTCTTTTCCATTGGAAAATCTTTAAAATGCACGTACTCACCATTTGTCTTTGCAGGGAAGG"
ins_36_SeqRec = SeqRecord(
    Seq(ins_36),
    id=fake_id,
    name="ABBACFFFFFFFGGGGGGGGGGGHGHGGHHHHHHHGHHHHGHHEFFEFGHHGHHHHGHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHGHHHHGGHHHFHGHFGHHHHGHHHHHGHHHHHHGGGHHHHHHHGHHGHHHHHHFHHFHFFGCDGHHHHHGHHHHFGHHHGGEGFHHHHHGFFFGHHHHGHHHHHDGHGHGGFEGGHHDFHHHHHGHECGHHHHHHHGGHHHHHHHHHGGHHGFFDD",
    description="+",
)
# 51bp - TTGATTTCAGAGAATATGAATTTGATTTCAGAGAATATGAATTTGATTTCAGAGAATATGAATTTGATTTCAGAGAATATGAAT
ins_51 = "GCAATTTAGGTATGAAAGCCAGCTACAGATGGTACAGGTGACCGGCTCCTCAGATAATGAGTACTTCTACGTTGATTTCAGAGAATATGAATTTGATTTCAGAGAATATGAATTTGATTTCAGAGAATATGAATTTGATTTCAGAGAATATGAATAAGAATGGAATGTGCCAAATGTTTCTGCAGCATTTCTTTTCCATTGGAAAATCTTTAAAATGCACGTACTCACCATTTGTCTTTGCAGGGAAGGCG"
ins_51_SeqRec = SeqRecord(
    Seq(ins_51),
    id=fake_id,
    name="ABBACFFFFFFFGGGGGGGGGGGHGHGGHHHHHHHGHHHHGHHEFFEFGHHGHHHHGHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHGHHHHGGHHHFHGHFGHHHHGHHHHHGHHHHHHGGGHHHHHHHGHHGHHHHHHFHHFHFFGCDGHHHHHGHHHHFGHHHGGEGFHHHHHGFFFGHHHHGHHHHHDGHGHGGFEGGHHDFHHHHHGHECGHHHHHHHGGHHHHHHHHHGGHHGFFDD",
    description="+",
)

## Functions
def make_ref_fastq(in_num_ref):
  ref_record_r1.letter_annotations["phred_quality"] = [30] * len(ref_record_r1)
  ref_record_r2.letter_annotations["phred_quality"] = [30] * len(ref_record_r2)
  object_list_r1 = [ref_record_r1 for _ in range(in_num_ref)]
  object_list_r2 = [ref_record_r2 for _ in range(in_num_ref)]
  with open("../test/REF_R1.fastq", "w") as output_handle:
      SeqIO.write(object_list_r1 , output_handle, "fastq")
  with open("../test/REF_R2.fastq", "w") as output_handle:
      SeqIO.write(object_list_r2, output_handle, "fastq")
  return 1

def make_spikein_fastq(in_mut_obj, in_ref_obj, in_num_mut, in_num_ref):
    print("Spiking-in to", in_num_ref," reads at a VAF of", in_num_mut/in_num_ref)
    in_ref_obj.letter_annotations["phred_quality"] = [30] * len(in_ref_obj)
    in_mut_obj.letter_annotations["phred_quality"] = [30] * len(in_mut_obj)
    object_list_r1 = [in_ref_obj for _ in range(in_num_ref)]
    object_list_mut = [in_mut_obj for _ in range(in_num_mut)]
    # Join REF and MUT
    end = in_num_ref - in_num_mut
    joined_record = object_list_r1[1:end] + object_list_mut
    out_path = "../test/TEST_MUT.fastq"
    with open(out_path, "w") as output_handle:
        SeqIO.write(joined_record, output_handle, "fastq")
    return 1


def main():
    # Make FASTQ with all reference reads
    #make_ref_fastq(1000000)

    # 1M reads; 1% VAF; 9bp INS
    #make_spikein_fastq(ins_9_SeqRec, ref_record_r1, 10000, 1000000)

    # 1M reads; 1% VAF; 21bp ITD
    #make_spikein_fastq(itd_21_SeqRec, ref_record_r1, 10000, 1000000)

    # 1M reads; 1% VAF; 36bp INS
    #make_spikein_fastq(ins_36_SeqRec, ref_record_r1, 10000, 1000000)

    # 1M reads; 1% VAF; 51bp ITD
    make_spikein_fastq(ins_51_SeqRec, ref_record_r1, 10000, 1000000)

if __name__ == "__main__":
    main()



